import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import { fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import DashboardPage from "@/app/components/indexlayout";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
        <html lang="en" suppressHydrationWarning>
        <head />
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}
        >
        <DashboardPage>
            {children}
        </DashboardPage>

        </body>
        </html>
      </>
  )
}
